'use client';

import React from 'react';
import { Box, Typography, Paper } from '@mui/material';
import NotificationsActiveIcon from '@mui/icons-material/NotificationsActive';
import ErrorOutlineIcon from '@mui/icons-material/ErrorOutline';
import BoltIcon from '@mui/icons-material/Bolt';
import CalloutBox from '../../common/CalloutBox';

const interruptTypes = [
  {
    token: 'info',
    icon: <BoltIcon sx={{ fontSize: 30, color: 'var(--info)' }} />,
    name: 'Hardware Interrupts (IRQs)',
    desc: 'Signals generated by physical devices — keyboard keypress, network packet arrival, disk I/O completion. The CPU pauses its current task, saves state, and runs the device\'s interrupt handler (ISR).',
    examples: 'Keyboard (IRQ 1), network card (IRQ 10–11), system timer (IRQ 0)',
    token2: 'info',
  },
  {
    token: 'warning',
    icon: <ErrorOutlineIcon sx={{ fontSize: 30, color: 'var(--warning)' }} />,
    name: 'Software Interrupts (Traps)',
    desc: 'Deliberately triggered by software via a special instruction (INT, SYSCALL). Used as the mechanism for system calls — the controlled way for user code to request kernel services.',
    examples: 'INT 0x80 (legacy Linux syscall), SYSCALL instruction, INT3 (debugger breakpoint)',
    token2: 'warning',
  },
  {
    token: 'danger',
    icon: <NotificationsActiveIcon sx={{ fontSize: 30, color: 'var(--danger)' }} />,
    name: 'Exceptions (Faults & Aborts)',
    desc: 'Raised by the CPU itself when something goes wrong during instruction execution. The kernel decides whether to handle the condition or terminate the offending process.',
    examples: 'Page fault (0x0E), divide-by-zero (0x00), general protection fault (0x0D), double fault',
    token2: 'danger',
  },
];

const idrFlow = [
  { step: '1', title: 'Interrupt signal', desc: 'Hardware asserts an IRQ line, or software executes a trap instruction.', token: 'info' },
  { step: '2', title: 'CPU saves context', desc: 'Registers, stack pointer, and flags are pushed to the kernel stack.', token: 'feature' },
  { step: '3', title: 'IDT lookup', desc: 'The Interrupt Descriptor Table maps the interrupt vector number to the correct handler address.', token: 'warning' },
  { step: '4', title: 'ISR executes', desc: 'The kernel\'s Interrupt Service Routine handles the event — acknowledging the device or processing the trap.', token: 'danger' },
  { step: '5', title: 'Context restored', desc: 'Saved registers are popped and the CPU resumes the interrupted task, as if nothing happened.', token: 'success' },
];

const securityNotes = [
  { label: 'Interrupt handler vulnerabilities', desc: 'Bugs in device drivers (ISRs) run at high privilege and can be exploited to gain kernel-mode code execution.' },
  { label: 'Interrupt storms (DoS)', desc: 'Flooding a device with interrupts can exhaust CPU time and freeze or crash the system.' },
  { label: 'NMI attacks', desc: 'Non-Maskable Interrupts cannot be blocked by software; attackers with physical access can abuse them.' },
  { label: 'Breakpoint injection', desc: 'INT3 (0xCC) is a single-byte breakpoint opcode. Debuggers and malware patch code in memory to intercept execution.' },
];

export default function InterruptHandlingConcept() {
  return (
    <Box sx={{ p: 3, maxWidth: 1000, mx: 'auto' }}>
      <Typography variant="h4" sx={{ mb: 2, fontWeight: 700, color: 'var(--ink)', textAlign: 'center' }}>
        Interrupt Handling and Exceptions
      </Typography>

      <Typography variant="body1" sx={{ mb: 4, color: 'var(--ink-soft)', textAlign: 'center', maxWidth: 760, mx: 'auto' }}>
        Interrupts are how the CPU responds to events that need immediate attention — a key press, a network
        packet, or an error. Understanding them is fundamental to both OS internals and security.
      </Typography>

      <Box sx={{ display: 'flex', gap: 3, flexWrap: 'wrap', justifyContent: 'center', mb: 5 }}>
        {interruptTypes.map((t) => (
          <Paper
            key={t.name}
            elevation={2}
            sx={{
              flex: '1 1 280px',
              maxWidth: 340,
              p: 3,
              borderRadius: 2,
              borderTop: `4px solid var(--${t.token})`,
            }}
          >
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, mb: 1 }}>
              {t.icon}
              <Typography variant="subtitle1" sx={{ fontWeight: 700, color: 'var(--ink)' }}>
                {t.name}
              </Typography>
            </Box>
            <Typography variant="body2" sx={{ color: 'var(--ink-soft)', lineHeight: 1.7, mb: 1 }}>
              {t.desc}
            </Typography>
            <Typography variant="caption" sx={{ color: 'var(--ink-soft)' }}>
              <strong style={{ color: 'var(--ink)' }}>Examples: </strong>{t.examples}
            </Typography>
          </Paper>
        ))}
      </Box>

      <Typography variant="h5" sx={{ fontWeight: 700, color: 'var(--ink)', textAlign: 'center', mb: 2 }}>
        Interrupt Dispatch Flow
      </Typography>
      <Typography variant="body2" sx={{ color: 'var(--ink-soft)', textAlign: 'center', mb: 3 }}>
        Every interrupt follows the same path through the Interrupt Descriptor Table (IDT).
      </Typography>

      <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1.5, mb: 5 }}>
        {idrFlow.map((s) => (
          <Paper
            key={s.step}
            elevation={1}
            sx={{
              display: 'flex',
              alignItems: 'flex-start',
              gap: 2,
              p: 2,
              borderRadius: 2,
              background: 'var(--paper-raised)',
              borderLeft: `4px solid var(--${s.token})`,
            }}
          >
            <Box
              sx={{
                flex: '0 0 auto',
                width: 32,
                height: 32,
                borderRadius: '50%',
                background: `var(--${s.token})`,
                color: 'var(--paper)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontWeight: 700,
              }}
            >
              {s.step}
            </Box>
            <Box>
              <Typography variant="subtitle1" sx={{ fontWeight: 700, color: 'var(--ink)' }}>
                {s.title}
              </Typography>
              <Typography variant="body2" sx={{ color: 'var(--ink-soft)' }}>
                {s.desc}
              </Typography>
            </Box>
          </Paper>
        ))}
      </Box>

      <Typography variant="h5" sx={{ fontWeight: 700, color: 'var(--ink)', textAlign: 'center', mb: 3 }}>
        Security Implications
      </Typography>

      <Box
        sx={{
          display: 'grid',
          gridTemplateColumns: { xs: '1fr', sm: '1fr 1fr' },
          gap: 2,
          mb: 4,
        }}
      >
        {securityNotes.map((s) => (
          <Paper
            key={s.label}
            elevation={1}
            sx={{ p: 2, borderRadius: 2, borderLeft: '4px solid var(--danger)', background: 'var(--paper-raised)' }}
          >
            <Typography variant="subtitle2" sx={{ fontWeight: 700, color: 'var(--ink)', mb: 0.5 }}>
              {s.label}
            </Typography>
            <Typography variant="body2" sx={{ color: 'var(--ink-soft)', lineHeight: 1.6 }}>
              {s.desc}
            </Typography>
          </Paper>
        ))}
      </Box>

      <CalloutBox type="info" title="Page faults as a security primitive">
        <Typography variant="body2" sx={{ color: 'var(--ink-soft)', lineHeight: 1.8 }}>
          The page-fault exception (0x0E) is used intentionally by modern OSes to implement
          copy-on-write memory, demand paging, and memory protection. When a process accesses a page it
          should not, the kernel terminates it with a segmentation fault. Security products can hook
          page-fault handlers to detect memory-scanning malware.
        </Typography>
      </CalloutBox>
    </Box>
  );
}
